## Module 8 DA- Working with NumPy (python)

### Q-1:- How to Creating a 3x3 Identity Matrix with Float Data Type? 

In [ ]:
import numpy as np

a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Q-2:- Create a 1D Array with Random Values between 0 and 1.

In [12]:
import numpy as np

random_values = np.random.rand(5)
random_values

array([0.92480672, 0.8346792 , 0.28238553, 0.69434623, 0.9361291 ])

### Q-3:- Create a 2D Array with Random Integer Values.

In [23]:
import numpy as np

random_int = np.random.randint(1,50,6).reshape(2,3)
random_int

array([[13, 27, 12],
       [36, 15, 18]], dtype=int32)

### Q-4:- Creating an Array Using a Custom Function.

In [2]:
import numpy as np

def custom_func(a,b):
    return a * b

array = np.fromfunction(custom_func,(3,3))
array

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

### Q-5:- Reshaping a 1D Array into a 2D Array 


In [4]:
import numpy as np

print("Before reshaping:")
a = np.array([1,2,3,4])
print(a)
print("After reshaping:-")
b = a.reshape(2,2)
print(b)


Before reshaping:
[1 2 3 4]
After reshaping:-
[[1 2]
 [3 4]]


In [54]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [55]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

### Q-6:- How to Creating a 3x3 Array of Ones? 


In [5]:
import numpy as np

ones_array = np.ones((3,3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Q-7:- How to get the common items between two pythons in NumPY
####          Input:
####           a = np. array ([1,2,3,2,3,4,3,4,5,6])
####           b = np. array ([7,2,10,2,7,4,9,4,9,8])
####          Expected Output:
####            array ([2, 4]) 
 


In [62]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np. array ([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

### Q-8:- From array a remove all items present in array 
#### Input:
####       a = np. array ([1,2,3,4,5])
####       b = np. array ([5,6,7,8,9])
#### Expected Output:
####       array ([1,2,3,4])

In [63]:
import numpy as np

a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9])

np.setdiff1d(a,b)


array([1, 2, 3, 4])

### Q-9:-  Limit the number of items printed in python NumPy array a to a maximum of 6 elements. 
#### a = np. arrange (15)
#### Expected Output:
####   array ([ 0, 1, 2, ..., 12, 13, 14] )


In [6]:
import numpy as np

a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Q-10:- Drop all nan values from a 1D NumPy
####       array Input:
####          np. array ([1,2,3, np.nan,5,6,7, np.nan])
####       Desired Output:
####         array ([ 1., 2., 3., 5., 6., 7.]) 

In [72]:
import numpy as np

a = np.array([1,2,3,np.nan,5,6,7,np.nan])

a[~ np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

### Q-11:- Create a 1D NumPy array of the first 20 natural numbers and a 2D NumPy array of shape (4, 5) with values ranging from 1 to 20.

In [9]:
import numpy as np

print("1D Array of first 20 natural numbers:")
array_1D = np.arange(1,21)
print(array_1D)

print("2D array of first 20 natural numbers:")
array_2D = array_1D.reshape(4,5)
print(array_2D)

1D Array of first 20 natural numbers:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2D array of first 20 natural numbers:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### Q-12:- Given a 3D NumPy array of shape (2, 3, 4), find its shape, size, number of dimensions, and data type. Change its data type to float64 and verify the change.

In [21]:
import numpy as np

a = np.arange(24).reshape(2,3,4)
print(a)
print(f"\nShape of array : {a.shape}")
print(f"Size of a array : {a.size}")
print(f"Number of dimension : {a.ndim}")
print(f"Data Type is : {a.dtype}")
a_floattype = a.astype(np.float64) 
print(f"\nChanged data type is :{a_floattype.dtype} ")
print("After changing its data type to float:")
print(a_floattype)
print(f"\nShape of array : {a_floattype.shape}")
print(f"Size of a array : {a_floattype.size}")
print(f"Number of dimension : {a_floattype.ndim}")
print(f"Data Type is : {a_floattype.dtype}")


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Shape of array : (2, 3, 4)
Size of a array : 24
Number of dimension : 3
Data Type is : int64

Changed data type is :float64 
After changing its data type to float:
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]

Shape of array : (2, 3, 4)
Size of a array : 24
Number of dimension : 3
Data Type is : float64


### Q-13:- Reshape a 1D array of 12 elements into a 3x4 2D array and then flatten it back into a 1D array using ravel (). Verify that the flattened array matches the original. 


In [23]:
import numpy as np

array_1D = np.arange(12)
print(array_1D)


print("\nReshaping in 2D array : ")
array_2D = array_1D.reshape(3,4)
print(array_2D)

print("\nFlatten back in 1d :")
flatten_array = np.ravel(array_2D)
print(flatten_array)

print("\nIs flatten array matches the original ?",{np.array_equal(array_1D,flatten_array)})


[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaping in 2D array : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flatten back in 1d :
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Is flatten array matches the original ? {True}


### Q-14:- Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4,5, 6]), perform element-wise addition, subtraction, multiplication, and division. Explain the behavior when dividing by zero

In [25]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition is :",np.add(a,b))
print("Subtraction is :",np.subtract(a,b))
print("Multiplication is :",np.multiply(a,b))
print("Division is :",np.divide(a,b))

b_zero = np.array([0,0,0])
divided_by_zero = a / b_zero
print("\nDivided by Zero is : ",divided_by_zero)

Addition is : [5 7 9]
Subtraction is : [-3 -3 -3]
Multiplication is : [ 4 10 18]
Division is : [0.25 0.4  0.5 ]

Divided by Zero is :  [inf inf inf]


C:\Users\POOJA SINGH\AppData\Local\Temp\ipykernel_2904\3126585448.py:12: RuntimeWarning: divide by zero encountered in divide
  divided_by_zero = a / b_zero


### Q-15:- Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform element-wise addition using broadcasting. Explain how broadcasting rules apply in this scenario

In [33]:
import numpy as np 
array_2d = np.arange(3).reshape(3,1)
print(array_2D)

array_1d = np.array([1,2,3]) 
print("\n",array_1d)

print("\nAddition of both arrays :\n",array_1d + array_2d)

[[0]
 [1]
 [2]]

 [1 2 3]

Addition of both arrays :
 [[1 2 3]
 [2 3 4]
 [3 4 5]]


How Broadcasting rules apply in above scenario?
-> Broadcasting allowed a (3,1) array and a (3,) array to be added without explicit reshaping.
-> The 1D array was expanded along the missing dimension to match the (3,1) shape.
-> The result is a (3,3) array.

### Q-16:- Generate a random 2D array of integers between 0 and 10. Use conditional operators to create a Boolean mask identifying elements greater than 5. Replace all elements greater than 5 with the value 5. 

In [49]:
import numpy as np

array_2D = np.random.randint(0,10,(2,5))
print("Original array :")
print(array_2D)

mask = np.where(array_2D > 5 , 5 ,array_2D)
print("\nAfter applying conditional operators : ")
print(mask)

Original array :
[[3 2 7 4 4]
 [2 6 2 9 0]]

After applying conditional operators : 
[[3 2 5 4 4]
 [2 5 2 5 0]]


### Q-17:-  Given a 4x4 array of random integers, use indexing and slicing to extract:
#### o The entire second row
#### o The last column
#### o The subarray consisting of the first two rows and first two columns 


In [60]:
import numpy as np

array = np.random.randint(1,17,(4,4))
print("Original array :\n",array)

second_row = array[1,::]
print("Second row :\n",second_row)

last_column = array[::,3]
print("Last Column :\n",last_column)

subarray = array[:2,:2]
print("Subarray consisting of the first two rows and first two columns :\n",subarray)

Original array :
 [[ 5  6 12 13]
 [ 9  4  4 15]
 [16  2 15 10]
 [ 8  2  2  6]]
Second row :
 [ 9  4  4 15]
Last Column :
 [13 15 10  6]
Subarray consisting of the first two rows and first two columns :
 [[5 6]
 [9 4]]


### Q-18:- Describe a practical example where NumPy can be used in EDA, AI, ML, and DL, and implement a NumPy solution for a simple task in each area.

### Q-19:- Create a random 4x4 matrix and use NumPy to compute its eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the matrix. 

### Q-20:- Create a 1D array of 27 elements and reshape it into a 3x3x3 3D array. Flatten it back into a 1D array and compare the flattened array with the original. 

In [70]:
array__1D = np.arange(27)
print("Original 1D array:\n",array__1D)

array__2D = array__1D.reshape(3,3,3)
print("After reshaping into 3D array :\n",array__2D)

flatten = array__2D.ravel()
print("Flatten Array is :\n",flatten)

print("Compare flattened array with the original: ",(np.array_equal(array__1D,flatten)))

Original 1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
After reshaping into 3D array :
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Flatten Array is :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
Compare flattened array with the original:  True


### Q-21:- Perform matrix multiplication of two 2D arrays using np.dot () and @. Compare the results and performance of both methods using a large dataset. 

### Q-22:- Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4,1). Perform an element-wise operation using broadcasting and explain the result. Use np. new axis to achieve the same result without broadcasting. 

In [21]:
import numpy as np

array_3d = np.arange(8).reshape(2,1,4)
array_2d = np.arange(4).reshape(4,1)
print("3-D array:\n",array_3d)
print("2-D array:\n",array_2d)

result_broadcasting = array_3d + array_2d
print("Result is :\n",result_broadcasting)
result_broadcasting.shape

3-D array:
 [[[0 1 2 3]]

 [[4 5 6 7]]]
2-D array:
 [[0]
 [1]
 [2]
 [3]]
Result is :
 [[[ 0  1  2  3]
  [ 1  2  3  4]
  [ 2  3  4  5]
  [ 3  4  5  6]]

 [[ 4  5  6  7]
  [ 5  6  7  8]
  [ 6  7  8  9]
  [ 7  8  9 10]]]


(2, 4, 4)

### Q-23:-  Generate a 2D array of random floats between 0 and 1. Use conditional operators to create a Boolean mask for values less than 0.5. Replace these values with their squares and leave the rest unchanged.

In [9]:
import numpy as np

array2D = np.random.rand(4,4)
print(array2D)

bool_mask = array2D < 0.5
array2D[bool_mask] = array2D[bool_mask] ** 2
print("\nModified array :\n",array2D)


[[0.10770035 0.29651974 0.82430306 0.40177829]
 [0.6216975  0.61105212 0.37967146 0.44910212]
 [0.7213033  0.57014628 0.43324468 0.25086151]
 [0.18238726 0.44958505 0.33608023 0.96968245]]

Modified array :
 [[0.01159937 0.08792396 0.82430306 0.1614258 ]
 [0.6216975  0.61105212 0.14415042 0.20169271]
 [0.7213033  0.57014628 0.18770096 0.0629315 ]
 [0.03326511 0.20212671 0.11294992 0.96968245]]


### Q-24:- Given a 5x5 array of sequential integers, use slicing to:
####            o Extract the diagonal elements
####            o Replace the elements of the middle row with zeros
####            o Flip the array vertically and horizontally

In [19]:
import numpy as np

array_5D = np.arange(25).reshape(5,5)
print("5-Dimensional Array : \n",array_5D)

#Extract the diagonal elements

diag_elements = np.diag(array_5D)
print("\nThe Diagonal elements : \n",diag_elements)

#Replace the elements of the middle row with zeros

array_5D[2,]=0
print("\nReplacing middle row with zeros:\n",array_5D)

#Flip the array vertically and horizontally

flipped_array = np.flip(array_5D)
print("\nAfter Flipping array :\n",flipped_array)


5-Dimensional Array : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The Diagonal elements : 
 [ 0  6 12 18 24]

Replacing middle row with zeros:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  0  0  0  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]

After Flipping array :
 [[24 23 22 21 20]
 [19 18 17 16 15]
 [ 0  0  0  0  0]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


### Q-24:- Create a 4D array of shape (2, 3, 4, 5) with random integers. Use advanced slicing to extract a subarray and compute the mean along a specified axis.

In [ ]:
import numpy as np

array_4D = np.random.randint(0,100,(2,3,4,5))
print("4 Dimensional Array :\n",array_4D)



4 Dimensional Array :
 [[[[43 25 59 82 65]
   [53 59 24 12 59]
   [11 34 34  1  8]
   [ 4 31 75 41 47]]

  [[72 65 65 85 92]
   [20 51 34 52 96]
   [70 18 84 51 84]
   [78 22  9  2 12]]

  [[92 38 94 48 72]
   [63 99 86 77 34]
   [19 46 26 51 75]
   [79  4 71 77 15]]]


 [[[75 27 65 96 81]
   [31 75 14 39 75]
   [30  8  9 95 41]
   [77 58 83 96 38]]

  [[89 25 72 36 43]
   [29 45 77 63 59]
   [95  1 56 11 13]
   [14 11 38 89 38]]

  [[78 82 96 71 44]
   [81 39 30 58 66]
   [15 69 11 60 88]
   [90 65 13 18 27]]]]


### Q-26:- Given an array of shape (10, 20), reshape it to (20, 10) and (5,40). Discuss the impact on the array's shape, size, and dimensionality. 

In [33]:
import numpy as  np
array_d = np.arange(200).reshape(10,20)
print("2 Dimensional Array :\n",array_d)

print("\nReshape to (20,10) :")
reshape_array = array_d.reshape(20,10)
print(reshape_array)

print("\nReshape to (5,40) :")
reshaped_array = array_d.reshape(5,40)
print(reshaped_array)



2 Dimensional Array :
 [[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]]

Reshape to (20,10) :
[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23 

#### Impact on the array's shape, size, and dimensionality. 

##### 1: Shape Change:
#####             The number of elements remains the same, but rows and columns are rearranged.
#####             (10, 20) → (20, 10): Just swaps rows and columns.
#####             (10, 20) → (5, 40): Merges some rows together into fewer, wider rows.
##### 2: Size Remains the same:
#####             Reshaping does not alter the number of elements.
##### 3: Dimensionality is Unchanged:
#####             The array remains 2D in all cases.

#### Q-27:- Generate a large 2D array and demonstrate the use of np. reshape() and unravel() to manipulate its shape for various linear algebra operations.

In [58]:
import numpy as np

array2d = np.random.randint(1,25,(4,6))
print("2 Dimensional Array :\n",array2d)

reshape = array2d.reshape(2,4,3)
print("\nAfter reshaping :")
print(reshape)

flattened = np.ravel(array2d)
print("\nFlattened Array :\n",flattened)

# max_index = np.argmax(flattened)
# unflattened = np.unravel_index(max_index,array2d.shape)
# print("\nAfter Flattened:\n",unflattened)

2 Dimensional Array :
 [[12 20 19 12 24 24]
 [ 1 24 18 21 17  3]
 [12  3 12 13 16 19]
 [ 9 15  2  4 23  6]]

After reshaping :
[[[12 20 19]
  [12 24 24]
  [ 1 24 18]
  [21 17  3]]

 [[12  3 12]
  [13 16 19]
  [ 9 15  2]
  [ 4 23  6]]]

Flattened Array :
 [12 20 19 12 24 24  1 24 18 21 17  3 12  3 12 13 16 19  9 15  2  4 23  6]


#### Q-28:- Given a 6x6 matrix, use advanced indexing and slicing to extract the upper triangular part of the matrix and set the lower triangular part to zero. Verify the result. 

In [66]:
import numpy as np

matrix = np.random.randint(1,36,(6,6))
print("6 Dimensional Matrix:\n",matrix)

upper_triangular = np.triu(matrix)
print("\nUpper Triangular Part of Matrix:\n",upper_triangular)

6 Dimensional Matrix:
 [[33 18 30 22 31  1]
 [27 10 21 29 31 17]
 [26 19 32 12 19 25]
 [26 17  4  2  8 20]
 [ 1 23 11  7 34  8]
 [ 4 28 32 17 18  8]]

Upper Triangular Part of Matrix:
 [[33 18 30 22 31  1]
 [ 0 10 21 29 31 17]
 [ 0  0 32 12 19 25]
 [ 0  0  0  2  8 20]
 [ 0  0  0  0 34  8]
 [ 0  0  0  0  0  8]]
